# 以下参数，可在https://dev.reecho.ai/introduction/overview找到
# 你在睿声获取的API，链接https://dev.reecho.ai/introduction/authentication
api_key: sk-XXXXXXXXXXXXXXXXXXXXXXXXX
# 参考睿声给出的模型，接着2024年2月2日，他们只给出下面这个model，链接https://dev.reecho.ai/generate/async
model: reecho-neural-voice-001
# 睿声给出的角色id，链接https://dash.reecho.ai/voices，这里以罗翔老师的为例
voice_id: 06887661-89a4-4196-bcb4-30b227e36277
# 多样性 (0-100)，参考https://dev.reecho.ai/generate/async
randomness: 97
# 稳定性过滤 (0-100，默认请填写0)，参考https://dev.reecho.ai/generate/async
stability_boost: 100
# 是否默认开启语音功能，默认为False
voice_switch: False
